name: Update Feeds

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # кожну годину

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run main.py
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add b2b.prom.*.xml.gz
          git commit -m "Update feeds [skip ci]" || echo "No changes to commit"
          git push
