name: Run main.py

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Show current directory
        run: pwd

      - name: List files in repo
        run: ls -la

      - name: Run main.py
        run: python main.py