on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # кожну годину

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

      - name: Run main.py
        run: python main.py
