name: Update Feeds

on:
  workflow_dispatch:        # ручний запуск
  schedule:
    - cron: "0 * * * *"     # запуск щогодини

permissions:
  contents: write           # дозволяє пушити зміни

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main.py
        run: |
          echo "Запускаю main.py..."
          python main.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          echo "📁 Статус перед комітом:"
          git status

          echo "📦 Додаю файли:"
          git add b2b.prom.*.xml.gz || echo "❌ Немає файлів для додавання"

          echo "📝 Коміт:"
          git commit -m "Update feeds [skip ci]" || echo "❌ Немає змін для коміту"

          echo "🚀 Пуш:"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main || echo "❌ Push failed"
